### ISSUE TITLE
feature windows 32bit support

### ISSUE THREAD

**Issue by foxever** [cakturk/go-netstat#14]
Is there any reason that only windows 64 bit is supported?

https://github.com/cakturk/go-netstat/blob/master/netstat/netstat_windows.go#L1

**Comment by cakturk** [comment]
No, but I haven't tested the code on a 32-bit Windows machine.
I'm not sure the memory layouts and alignment requirements are
the same. If you tested it on a 32-bit Windows machine and you
are sure it works, we can remove the build constraint.

**Comment by foxever** [comment]
> No, but I haven't tested the code on a 32-bit Windows machine.
> I'm not sure the memory layouts and alignment requirements are
> the same. If you tested it on a 32-bit Windows machine and you
> are sure it works, we can remove the build constraint.

I have test 32-bit binary (build on ubuntu 18.04) on windows 10 64-bit and it works fine, I think it should work if remove the build constrain

```bash
$ GOOS=windows GOARCH=386 go build -o go-netstat.exe main.go
$ file go-netstat.exe
go-netstat.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
```

and it works
```bash
❯ .\go-netstat.exe -lis
Not all processes could be identified, you would have to be root to see it all.
Proto Local Addr              Foreign Addr            State        PID/Program name
tcp   0.0.0.0:135             0.0.0.0:0               LISTEN       1420/svchost.exe
```

**Comment by foxever** [comment]
> No, but I haven't tested the code on a 32-bit Windows machine.
> I'm not sure the memory layouts and alignment requirements are
> the same. If you tested it on a 32-bit Windows machine and you
> are sure it works, we can remove the build constraint.

I have test 32-bit binary (build on ubuntu 18.04) on windows 10 64-bit and it works fine, I think it should work if remove the build constrain

```bash
$ GOOS=windows GOARCH=386 go build -o go-netstat.exe main.go
$ file go-netstat.exe
go-netstat.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
```

and it works
```bash
❯ .\go-netstat.exe -lis
Not all processes could be identified, you would have to be root to see it all.
Proto Local Addr              Foreign Addr            State        PID/Program name
tcp   0.0.0.0:135             0.0.0.0:0               LISTEN       1420/svchost.exe
```

**Comment by InsipidJC** [comment]
I tested on windows 11 (change the GOARCH from amd64 to 386),  the compilation failed.
```
\> go env -w GOARCH=386
\> go build -o go-netstat.exe .\test-netstat.go
\# github.com/cakturk/go-netstat/netstat
netstat\\netstat.go:42:9: undefined: skStates
netstat\\netstat.go:55:9: undefined: osTCPSocks
netstat\\netstat.go:61:9: undefined: osTCP6Socks
netstat\\netstat.go:67:9: undefined: osUDPSocks
netstat\\netstat.go:73:9: undefined: osUDP6Socks 
```
